[build.environment]
  NPM_FLAGS="--prefix=/dev/null"
  YARN_FLAGS="--prefix=/dev/null"
[build]
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm run build --filter demo... --stream"
  publish = "build"
